package com.fbu.autonote.fragments;

import android.content.Context;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.fbu.autonote.R;
import com.fbu.autonote.adapters.ScanResultAdapter;
import com.geniusscansdk.scanflow.ScanResult;
import com.google.android.material.progressindicator.LinearProgressIndicator;

import org.jetbrains.annotations.NotNull;

import java.util.List;

/**
 * Manages images generated by the Scanner SDK and shows them on a grid layout along with indicators
 * that signal the user their data is being uploaded
 */
public class ScanResultsFragment extends Fragment {
    Context context;
    ScanResultAdapter scansAdapter;
    GridLayoutManager gridLayoutManager;
    RecyclerView rvScanResults;
    LinearProgressIndicator progressIndicator;
    public static final String TAG = "ScanResultsFragment";
    public List<ScanResult.Scan> scans;

    //Required empty constructor
    public ScanResultsFragment() {
    }

    public static ScanResultsFragment newInstance(List<ScanResult.Scan> scans) {
        ScanResultsFragment fragment = new ScanResultsFragment();
        Bundle args = new Bundle();
        //Pass the pointer of the list to avoid data duplication
        fragment.scans = scans;
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        Log.d(TAG, "scanner fragment initiated!");
        super.onCreate(savedInstanceState);
        //Avoids excessive function calling
        context = getContext();
        Log.d(TAG, "SCANS LEN: " + scans.size());
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_scan_results, container, false);
    }

    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        //Setup recyclerview, adapter and manager
        progressIndicator = view.findViewById(R.id.progressIndicator);
        progressIndicator.show();
        rvScanResults = view.findViewById(R.id.rvScanResults);
        gridLayoutManager = new GridLayoutManager(context, 3);
        scansAdapter = new ScanResultAdapter(context, scans);
        rvScanResults.setAdapter(scansAdapter);
        rvScanResults.setLayoutManager(gridLayoutManager);
    }


}